##
# Почти CODEOWNERS, только работает лучше. 
# Реквестит ревью указанных людей/команд при изменениях в указанных файлах/папках. Названия команд начинаются с "/", пути от корневой папки.
#
# Вы должны быть частью команды гитхаб-организации, иначе гитхаб не сможет назначить вас на ревью.
# Так что запросите у мейнтейнеров инвайт в группу Collaborators, если необходимо.
#
# Держите файлы и папки в алфавитном порядке (так, как они отсортированны в DreamMaker и taucetistation.dme).
#
# CODEOWNERS используются у нас ТОЛЬКО ДЛЯ УВЕДОМЛЕНИЙ, если вы хотите закрепить за собой обязательность 
# ревью PR-а перед мержем - напишите об этом дополнительно в PR, желательно в первые сутки его открытия!
#
##

components:
  ## Код ##
  
  # /code/
  code/modules/client/preferences_savefile.dm: volas

  ## Конфиги ##
  config/: volas

  ## Иконки ##
  icons/:
    /sprites-department

  ## Карты ##
  maps/testmap/testmap.dmm: volas

  ## TGUI ##
  # tgui/: вы

  ## Общее ##
  "*.py": volas
  "*.sh": volas

 .github/: /maintainers

ignored-authors:
  - dependabot
  - renovate-bot
