/obj/structure/safe/floor/blueshield
	name = "blueshield safe"
	number_of_tumblers = 4

/obj/structure/safe/floor/blueshield/check_unlocked()
	if(current_tumbler_index > number_of_tumblers)
		if (!(get_security_level() in list("red", "delta")))
			to_chat(usr, "<span class='italics'Этот сейф можно открыть только при красном или Дельта коде.</span>")
			return FALSE
	return ..()

/obj/structure/safe/floor/blueshield/examine(mob/user)
	..()
	var/mob/living/carbon/human/H = user
	if(H.isimplantedblueshield())
		to_chat(H, "<span class='notice'>Вы вспоминаете код от сейфа, полученный во время инструктажа... [get_combination()].</span>")

/obj/structure/safe/floor/blueshield/PopulateContents()
	switch(rand(1, 5))
		if(1)
			new /obj/item/clothing/head/helmet/space/rig/blueshield(src)
			new /obj/item/clothing/suit/space/rig/blueshield(src)
			new /obj/item/weapon/tank/emergency_oxygen/double(src)
		if(2)
			new /obj/item/weapon/storage/firstaid/blueshield(src)
		if(3)
			new /obj/item/weapon/gun/projectile/automatic/l13(src)
			for (var/i in 1 to 2)
				new /obj/item/ammo_box/magazine/l13(src)
			for (var/i in 1 to 3)
				new /obj/item/ammo_box/magazine/l13/lethal(src)
		if(4)
			new /obj/item/weapon/fireaxe/blue(src)
		if(5)
			new /obj/item/weapon/reagent_containers/food/snacks/pastatomato(src)
			new /obj/item/weapon/reagent_containers/food/snacks/salmonsteak(src)
			new /obj/item/weapon/reagent_containers/food/snacks/tossedsalad(src)
			new /obj/item/weapon/reagent_containers/food/snacks/sliceable/cake/chocolate(src)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/wine(src)
			for (var/i in 1 to 3)
				new /obj/item/weapon/reagent_containers/food/drinks/drinkingglass(src)
			new /obj/item/weapon/storage/visuals/tray(src)
		if(6)
			new /obj/item/weapon/storage/secure/briefcase/syndie(src)
		if(7)
			for (var/i in 1 to 6)
			new /obj/item/weapon/reagent_containers/food/snacks/grown/bluespacetomato(src)
		if(8)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/holywater(src)
			new /obj/item/clothing/accessory/metal_cross(src)
			new /obj/item/weapon/storage/bible(src)
		if(9)
			new /obj/item/weapon/gun/projectile/shotgun/combat/nonlethal(src)
			new /obj/item/ammo_box/eight_shells(src)
			new /obj/item/ammo_box/eight_shells/buckshot(src)
			new /obj/item/ammo_box/eight_shells/incendiary(src)
			new /obj/item/ammo_box/eight_shells/stunshot(src)
		if(9)
			new /obj/item/weapon/gun/projectile/revolver(src)
			new /obj/item/ammo_box/speedloader/a357(src)
			new /obj/item/ammo_box/speedloader/a357(src)
		if(10)
			new /obj/item/weapon/gun/projectile/automatic/glock/spec(src)
			new /obj/item/ammo_box/magazine/glock/extended(src)
		if(11)
			var/obj/item/weapon/gun/projectile/revolver/R = new /obj/item/weapon/gun/projectile/revolver(src)
			while(R.get_ammo() > 0)
				var/obj/item/ammo_casing/C
				C = R.magazine.get_round(0)
				R.chambered = null
				QDEL_NULL(C)
			new /obj/item/ammo_casing/a357(src)
		if(12)
			new /obj/item/weapon/storage/toolbox/mechanical(src)
		if(13)
			for (var/i in 1 to 3)
				new /obj/item/ammo_box/magazine/glock/extended/rubber(src)
			for (var/i in 1 to 3)
				new /obj/item/ammo_box/magazine/glock/extended(src)
		if(14)
			new /obj/item/weapon/gun/projectile/revolver/rocketlauncher(src)
		if(15)
			var/obj/item/weapon/storage/lockbox/anti_singulo/A = new /obj/item/weapon/storage/lockbox/anti_singulo(src)
			A.req_access = list(access_blueshield)
		if(16)
			for (var/i in 1 to 3)
				new /obj/item/weapon/reagent_containers/food/snacks/grown/banana(src)
			new /obj/item/weapon/reagent_containers/food/snacks/grown/banana/honk(src)
			new /obj/item/weapon/bikehorn(src)
		if(17)
			new /obj/item/weapon/gun/grenadelauncher(src)
		if(18)
			new /obj/item/weapon/gun/medbeam(src)
		if(19)
			new /obj/item/weapon/gun/projectile/grenade_launcher/m79(src)
			new /obj/item/weapon/storage/box/r4046/teargas(src)
			new /obj/item/weapon/storage/box/r4046/rubber(src)
		if(20)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/vodka(src)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/cognac(src)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/rum(src)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/wine(src)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/tequilla(src)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/kahlua(src)
			new /obj/item/weapon/reagent_containers/food/drinks/bottle/beer(src)
			new /obj/item/weapon/storage/box/drinkingglasses(src)
		if(21)
			new /obj/item/clothing/head/helmet/tactical/marinad(src)
			new /obj/item/clothing/suit/marinad(src)
			new /obj/item/clothing/under/tactical/marinad(src)
			new /obj/item/weapon/storage/backpack/dufflebag/marinad(src)
			new /obj/item/clothing/gloves/security/marinad(src)
			new /obj/item/weapon/gun/projectile/revolver/mateba(src)
		if(22)
			new /obj/item/weapon/reagent_containers/pill/adminordrazine(src)
		if(23)
			new /obj/item/clothing/gloves/combat(src)
			new /obj/item/clothing/shoes/boots/combat(src)
		if(24)
			new /obj/item/weapon/gun/projectile/automatic(src)
			new /obj/item/ammo_box/magazine/smg(src)
			new /obj/item/ammo_box/magazine/smg(src)
			new /obj/item/clothing/mask/balaclava(src)
			new /obj/item/clothing/suit/armor/vest/fullbody(src)
			new /obj/item/clothing/gloves/black(src)
		if(25)
			new /obj/item/weapon/reagent_containers/food/snacks/sliceable/cake/birthday(src)
