/obj/random/syndie/fullhouse/item_to_spawn()
	name = "Random Syndicate Item"
	desc = "This is random syndicate item."
	icon = 'icons/obj/items.dmi'
	icon_state = "soapsyndie"
	return pick(\
	prob(2);/obj/item/weapon/gun/projectile/automatic/l6_saw,\
	prob(3);/obj/item/weapon/antag_spawner/borg_tele,\
	prob(3);/obj/item/weapon/gun/projectile/revolver/rocketlauncher,\
	prob(4);/obj/item/weapon/gun/projectile/automatic/a74,\
	prob(5);/obj/item/weapon/storage/box/syndie_kit/imp_uplink,\
	prob(5);/obj/item/weapon/storage/box/syndicate,\
	prob(5);/obj/item/toy/syndicateballoon,\
	prob(5);/obj/item/weapon/gun/projectile/heavyrifle,\
	prob(6);/obj/item/weapon/shield/energy,\
	prob(6);/obj/item/weapon/gun/projectile/automatic/bulldog,\
	prob(7);/obj/item/device/radio/beacon/syndicate,\
	prob(7);/obj/item/ammo_box/magazine/m762,\
	prob(8);/obj/item/weapon/aiModule/freeform/syndicate,\
	prob(8);/obj/item/device/powersink,\
	prob(8);/obj/item/device/radio/beacon/syndicate_bomb,\
	prob(10);/obj/item/weapon/storage/firstaid/tactical,\
	prob(10);/obj/item/ammo_casing/caseless/rocket,\
	prob(10);/obj/item/ammo_casing/caseless/rocket/emp,\
	prob(12);/obj/item/weapon/melee/powerfist,\
	prob(12);/obj/item/weapon/gun/projectile/revolver ,\
	prob(14);/obj/item/weapon/gun/projectile/automatic/c20r,\
	prob(14);/obj/item/weapon/implanter/storage,\
	prob(14);/obj/item/weapon/gun/energy/crossbow,\
	prob(14);/obj/item/weapon/melee/energy/sword,\
	prob(14);/obj/item/ammo_box/magazine/a74mm,\
	prob(14);/obj/item/weapon/grenade/spawnergrenade/manhacks,\
	prob(14);/obj/item/device/healthanalyzer/rad_laser,\
	prob(16);/obj/item/weapon/gun/projectile/automatic/pistol,\
	prob(16);/obj/item/weapon/grenade/syndieminibomb,\
	prob(16);/obj/item/weapon/storage/box/syndie_kit/throwing_weapon,\
	prob(16);/obj/item/weapon/card/emag,\
	prob(20);/obj/item/weapon/storage/box/emps,\
	prob(20);/obj/item/weapon/storage/box/syndie_kit/imp_freedom,\
	prob(20);/obj/item/ammo_box/magazine/m12g/incendiary,\
	prob(20);/obj/item/device/chameleon,\
	prob(20);/obj/item/weapon/storage/box/syndie_kit/space,\
	prob(20);/obj/item/clothing/glasses/thermal/syndi,\
	prob(20);/obj/item/weapon/storage/firstaid/small_firstaid_kit/combat,\
	prob(20);/obj/item/weapon/pen/edagger,\
	prob(20);/obj/item/device/encryptionkey/binary,\
	prob(25);/obj/item/weapon/storage/backpack/dufflebag/surgery,\
	prob(25);/obj/item/weapon/storage/backpack/dufflebag/c4,\
	prob(25);/obj/item/weapon/reagent_containers/syringe/mulligan,\
	prob(25);/obj/item/device/flashlight/emp,\
	prob(25);/obj/item/ammo_box/magazine/m12g,\
	prob(25);/obj/item/ammo_box/magazine/m12g/stun,\
	prob(25);/obj/item/weapon/pen/paralysis,\
	prob(25);/obj/item/weapon/card/id/syndicate,\
	prob(33);/obj/item/weapon/grenade/clusterbuster/soap,\
	prob(33);/obj/item/ammo_box/magazine/borg45,\
	prob(33);/obj/item/ammo_box/a357,\
	prob(33);/obj/item/device/encryptionkey/binary,\
	prob(33);/obj/item/clothing/mask/gas/voice,\
	prob(33);/obj/item/clothing/gloves/black/strip,\
	prob(50);/obj/item/device/encryptionkey/syndicate,\
	prob(50);/obj/item/device/multitool/ai_detect,\
	prob(50);/obj/item/device/syndicatedetonator,\
	prob(50);/obj/item/ammo_box/magazine/m12mm,\
	prob(50);/obj/item/ammo_box/magazine/m9mm,\
	prob(50);/obj/item/weapon/storage/fancy/cigarettes/cigpack_syndicate,\
	prob(50);/obj/item/weapon/cartridge/syndicate,\
	prob(50);/obj/item/toy/carpplushie/dehy_carp,\
	prob(50);/obj/item/weapon/storage/box/syndie_kit/chameleon,\
	prob(50);/obj/item/device/camera_bug,\
	prob(50);/obj/item/weapon/silencer,\
	prob(50);/obj/item/ammo_casing/a145,\
	prob(50);/obj/item/weapon/gun/syringe/syndicate,\
	prob(100);/obj/item/weapon/storage/secure/briefcase/syndie,\
	prob(100);/obj/item/weapon/plastique,\
	prob(100);/obj/item/weapon/storage/backpack/satchel/flat,\
	prob(100);/obj/item/clothing/shoes/syndigaloshes,\
	prob(100);/obj/item/weapon/storage/belt/military,\
	prob(100);/obj/item/weapon/storage/toolbox/syndicate,\
	prob(100);/obj/item/weapon/soap/syndie,\
	prob(100);/obj/item/weapon/storage/box/syndie_kit/cutouts,\
	prob(100);/obj/item/weapon/reagent_containers/food/snacks/donkpocket,\
	prob(100);/obj/item/weapon/reagent_containers/food/snacks/syndicake\
	)
