/mob/living/carbon/human/bum/New()
	..()
	generate_random_bum()

/mob/living/carbon/human/proc/generate_random_bum()
	var/obj/randomcatcher/CATCH = new /obj/randomcatcher(src)
	if(prob(75))
		equip_to_slot_or_del(CATCH.get_item(/obj/random/cloth/under), slot_w_uniform)
	if(prob(50))
		equip_to_slot_or_del(CATCH.get_item(/obj/random/cloth/shoes), slot_shoes)
	if(prob(25))
		equip_to_slot_or_del(CATCH.get_item(/obj/random/cloth/backpack), slot_back)
	if(prob(25))
		equip_to_slot_or_del(CATCH.get_item(/obj/random/cloth/gloves), slot_gloves)
	if(prob(25))
		equip_to_slot_or_del(CATCH.get_item(/obj/random/cloth/randomsuit), slot_wear_suit)
	if(prob(25))
		equip_to_slot_or_del(CATCH.get_item(/obj/random/cloth/randomhead), slot_head)
	equip_to_slot_or_del(new /obj/item/weapon/shovel(src), slot_l_hand)
	for(var/obj/item/loot in contents)
		loot.make_old()
	qdel(CATCH)
	gender = pick(MALE, FEMALE)
	if(gender == MALE)
		name = pick(first_names_male)
	else
		name = pick(first_names_female)
	name += " [pick(last_names)]"
	real_name = name
	var/datum/preferences/A = new()	//Randomize appearance for the human
	A.randomize_appearance_for(src)
	update_inv_head()
	update_inv_wear_suit()
	update_inv_gloves()
	update_inv_shoes()
	update_inv_w_uniform()
	update_inv_l_hand()