name: "Сообщить о проблеме"
description: "Если что-то работает не так, как ожидалось."
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: "## Пожалуйста, не стирайте строчки, которые были автоматически созданы."

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите одну проблему как можно подробнее"
      value: |
        #### Что должно было произойти

        #### Что произошло на самом деле

  - type: textarea
    id: reproduction
    attributes:
      label: "Шаги воспроизведения"
      description: "Если приемлемо, опишите шаги для воспроизведения проблемы"
      placeholder: |
        1. Найти автолат
        2. Открыть его меню, кликнул ЛКМ
        3. Получить лаги

  - type: textarea
    id: additional
    attributes:
      label: "Дополнительная информация:"
      description: |
        Вы можете добавьте скриншоты, чтобы помочь описать вашу проблему
        **Подсказка**: Вы можете прикрепить изображения, щелкнув по области ниже для её выделения,
         а затем перетащите в неё файлы
