name: "Сообщить о проблеме на карте"
title: "[Название карты или локации] "
description: "Если что-то не так с картой"
labels: ["Bug", "Map Issue"]
body:
  - type: markdown
    attributes:
      value: "## Пожалуйста, не стирайте строчки, которые были автоматически созданы."

  - type: textarea
    id: reproduction
	validations:
      required: true
    attributes:
      label: "В какой локации это произошло?"
      description: "Укажите станцию или локацию на которой вы нашли мапперскую ошибку"
      placeholder: |
	  Исход
	  Гамма
	  Астероид
	  Астероид Прометея
	  Дирелект с базой советов
	  База Синдиката

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Опишите, что по вашему не так на карте?"
      description: "Опишите обнаруженную вами проблему на одной из локаций"
      placeholder: |
	  	На аванпост шахтёров невозможно попасть из-за стены в шлюзах доков


  - type: textarea
    id: additional
    attributes:
      label: "Дополнительная информация:"
      description: |
        Вы можете добавьте скриншоты, чтобы помочь описать вашу проблему
        **Подсказка**: Вы можете прикрепить изображения, щелкнув по области ниже для её выделения,
         а затем перетащите в неё файлы
