name: "Сообщить о проблеме на карте"
title: "[Название карты или локации] "
description: "Если что-то не так с картой"
labels: ["Bug", "Map Issue"]
body:
  - type: textarea
    id: location
    validations:
      required: true
    attributes:
      label: "В какой локации это произошло?"
      description: "Укажите станцию или локацию на которой вы нашли мапперскую ошибку"
      placeholder: |
        Исход
        Гамма
        Астероид
        Астероид Прометея
        Дирелект с базой советов
        База Синдиката

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите обнаруженную вами проблему на одной из локаций"
      placeholder: |
        На аванпост шахтёров невозможно попасть из-за стены в шлюзах доков
