name: "Сообщить об ошибке в тексте или переводе"
description: "Некорректный текст или перевод на русский язык."
labels: ["Bug", "Translation/Localization"]
body:
  - type: markdown
    attributes:
      value: "## Пожалуйста, не стирайте строчки, которые были автоматически созданы."


  - type: textarea
    id: location
    validations:
      required: true
    attributes:
      label: "Где вы нашли ошибку?"
      description: "Укажите, где вы нашли ошибку в тексте: (Интерфейс консоли, описание предмета, некорректные комбат логи и т.п.)"
      placeholder: |
        Интерфейс консоли шаттла
        Описание ручного сканера
        Некорректный лог от выстрела из тазера
        Оповещение импланта о смерти

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите обнаруженную ошибку в тексте как можно подробнее"
      value: |
        #### Как должно было звучать/переведено
        AYS установил аккумулятор в электрический щит криогенных камер!

        #### Что произошло на самом деле
        AYS установил аккумулятор в электрический щит криогенных камерах!

  - type: textarea
    id: reproduction
    attributes:
      label: "Шаги воспроизведения"
      description: "Если приемлемо, опишите шаги для воспроизведения проблемы в тексте"
      placeholder: |
        1. Вытащить батарейку из электрического щита
        2. После вставить обратно батарейку
        3. Увидеть некорректный перевод данного лога

  - type: textarea
    id: additional
    attributes:
      label: "Дополнительная информация:"
      description: |
        Вы можете добавьте скриншоты, чтобы помочь описать вашу проблему
        **Подсказка**: Вы можете прикрепить изображения, щелкнув по области ниже для её выделения,
         а затем перетащите в неё файлы
