#define MAX_INSURANCE_PRICE 5000

#define INSURANCE_NONE "None"
#define INSURANCE_STANDARD "Standard"
#define INSURANCE_PREMIUM "Premium"

#define STARTING_MONEY_MULTIPLYER 3
#define STARTING_MONEY_VARIANCE 5 //in percents
#define STARTING_MONEY_MINIMUM 50
