#define REPLICATOR_COST_REPLICATE 100
#define REPLICATOR_COST_TRANSPONDER REPLICATOR_COST_REPLICATE

#define REPLICATOR_BANDWIDTH_COST_INCREASE 50

#define REPLICATORS_CATAPULTED_TO_WIN 20

#define REPLICATOR_STATE_HARVESTING "harvesting"
#define REPLICATOR_STATE_HELPING "helping"
#define REPLICATOR_STATE_WANDERING "wandering"
#define REPLICATOR_STATE_GOING_TO_HELP "going_to_help"
#define REPLICATOR_STATE_COMBAT "combat"

#define REPLICATOR_COLORS list("#A8DFF0", "#F0A8DF", "#DFF0A8")

// Disintegration unit time modifiers.
#define REPLICATOR_TICKS_PER_MATERIAL 16.0
#define REPLICATOR_RECLAIM_OWN_STRUCTURES_TICK_MODIFIER 0.25
#define REPLICATOR_RECLAIM_REPLICATOR_TICK_MODIFIER 0.1
#define REPLICATOR_PUNISH_GRIEFING_TICK_MODIFIER 4.0
#define REPLICATOR_REWARD_CONDUCTIVE_TICK_MODIFIER 0.5
#define REPLICATOR_REWARD_STACKS_TICK_MODIFIER 0.5

// Power usage.
#define REPLICATOR_TRANSPONDER_POWER_USAGE 10000
#define REPLICATOR_CATAPULT_POWER_USAGE 40000
#define REPLICATOR_GENERATOR_POWER_GENERATION 30000

#define REPLICATOR_MAX_CONTROLLED_DRONES 4

// How many materials do Transponders transfer per tick.
#define REPLICATOR_TRANSPONDER_CONSUMPTION_RATE 2.0

// How much health per material unit.
#define REPLICATOR_DISINTEGRATION_REPAIR_RATE 2.0
