#define REPLICATOR_COST_REPLICATE 100
#define REPLICATOR_COST_TRANSPONDER REPLICATOR_COST_REPLICATE
#define REPLICATOR_COST_GENERATOR REPLICATOR_COST_REPLICATE
#define REPLICATOR_COST_MINE 30
#define REPLICATOR_COST_BARRICADE 15
	// Because they also autospawn when breaking airlocks.
	#define REPLICATOR_COST_RECLAIM_BARRICADE 5

#define REPLICATOR_BANDWIDTH_COST_INCREASE 50

#define REPLICATORS_CATAPULTED_TO_WIN 20

#define REPLICATOR_STATE_HARVESTING "harvesting"
#define REPLICATOR_STATE_HELPING "helping"
#define REPLICATOR_STATE_WANDERING "wandering"
#define REPLICATOR_STATE_GOING_TO_HELP "going_to_help"
#define REPLICATOR_STATE_COMBAT "combat"

#define REPLICATOR_COLORS list("#ffffff", "#ff5555", "#55ff55", "#5555ff", "#ffff55", "#ff55ff", "#55ffff", "#ff9999", "#99ff99", "#9999ff", "#ffff99", "#ff99ff", "#99ffff")
#define REPLICATOR_RUNE_COLORS list("#a8dff0", "#f0a8df", "#dff0a8")

// Disintegration unit time modifiers.
#define REPLICATOR_TICKS_PER_MATERIAL 16.0
#define REPLICATOR_RECLAIM_OWN_STRUCTURES_TICK_MODIFIER 0.25
#define REPLICATOR_RECLAIM_REPLICATOR_TICK_MODIFIER 0.1
#define REPLICATOR_REWARD_CONDUCTIVE_TICK_MODIFIER 0.5
#define REPLICATOR_REWARD_STACKS_TICK_MODIFIER 0.5
#define REPLICATOR_REWARD_DEAD_BODIES_TICK_MODIFIER 0.5
#define REPLICATOR_PUNISH_GRIEFING_TICK_MODIFIER 4.0
#define REPLICATOR_PUNISH_LIVE_MOBS_TICK_MODIFIER 2.0

// Power usage.
#define REPLICATOR_TRANSPONDER_POWER_USAGE 10000
#define REPLICATOR_CATAPULT_POWER_USAGE 40000
#define REPLICATOR_GENERATOR_POWER_GENERATION 30000

#define REPLICATOR_MAX_CONTROLLED_DRONES 4

// How many materials do Transponders transfer per tick.
#define REPLICATOR_TRANSPONDER_CONSUMPTION_RATE 2.0

// How much health per material unit.
#define REPLICATOR_DISINTEGRATION_REPAIR_RATE 2.0

#define REPLICATOR_STARTING_BANDWIDTH 6
#define REPLICATOR_MAX_BANDWIDTH 50

// Rewarding killing mobs.
#define REPLICATOR_MATERIAL_AMOUNT_COEFF_ORGANIC 4.0

// Upgrade defines.
#define REPLICATOR_UPGRADE_CATEGORY_OFFENSIVE "Offensive"
#define REPLICATOR_UPGRADE_CATEGORY_DEFENSIVE "Defensive"
#define REPLICATOR_UPGRADE_CATEGORY_SUPPORT "Support"
#define REPLICATOR_UPGRADE_CATEGORIES list(REPLICATOR_UPGRADE_CATEGORY_OFFENSIVE, REPLICATOR_UPGRADE_CATEGORY_DEFENSIVE, REPLICATOR_UPGRADE_CATEGORY_SUPPORT)
#define REPLICATOR_STARTING_UPGRADE_POOL list(\
	/datum/replicator_array_upgrade/offensive/ranged_attack_damage,\
	/datum/replicator_array_upgrade/defensive/max_health_points,\
	/datum/replicator_array_upgrade/support/efficency,\
)
