//Prefs for ignore a question which give special_roles
#define IGNORE_PAI          "Pai"
#define IGNORE_TSTAFF       "Religion staff"
#define IGNORE_SURVIVOR     "Survivor"
#define IGNORE_POSBRAIN     "Positronic brain"
#define IGNORE_DRONE        "Drone"
#define IGNORE_NARSIE_SLAVE "Nar-sie slave"
#define IGNORE_SYNDI_BORG   "Syndicate robot"
#define IGNORE_LARVA        "Larva"
#define IGNORE_EVENT_BLOB   "Event blob"
#define IGNORE_EMINENCE     "Eminence"
