#define TEMPLATE_GENERIC "0"
#define TEMPLATE_SHELTER "1"
#define TEMPLATE_HOLO    "2"
#define TEMPLATE_DEPT    "3"


#define TEMPLATE_DEPT_GENERIC     "0"
#define TEMPLATE_DEPT_ENGINEERING "1"


#define GET_TEMPLATE_DEPT_LIST(DEPARTMENT) map_templates_categorized[TEMPLATE_DEPT][DEPARTMENT]
#define CHECK_DEPT_LIST_EXIST(DEPARTMENT) if(!GET_TEMPLATE_DEPT_LIST(DEPARTMENT)) return
#define GET_RANDOM_VALUE_FROM_TEMPLATE_DEPT_LIST(DEPARTMENT) GET_TEMPLATE_DEPT_LIST(DEPARTMENT)[pick(GET_TEMPLATE_DEPT_LIST(DEPARTMENT))]