// Artifact effect defines
#define EFFECT_TOUCH 0
#define EFFECT_AURA 1
#define EFFECT_PULSE 2
#define MAX_EFFECT 2

// Artifact trigger defines
#define TRIGGER_TOUCH 0
#define TRIGGER_WATER 1
#define TRIGGER_ACID 2
#define TRIGGER_VOLATILE 3
#define TRIGGER_TOXIN 4
#define TRIGGER_FORCE 5
#define TRIGGER_ENERGY 6
#define TRIGGER_HEAT 7
#define TRIGGER_COLD 8
#define TRIGGER_PHORON 9
#define TRIGGER_OXY 10
#define TRIGGER_CO2 11
#define TRIGGER_NITRO 12
#define TRIGGER_VIEW 13
#define MAX_TRIGGER 13

// Artifact icon_num defines
#define ARTIFACT_WIZARD_LARGE 1
#define ARTIFACT_WIZARD_SMALL 2
#define ARTIFACT_MARTIAN_LARGE 3
#define ARTIFACT_MARTIAN_SMALL 4
#define ARTIFACT_MARTIAN_PINK 5
#define ARTIFACT_CUBE 6
#define ARTIFACT_PILLAR 7
#define ARTIFACT_COMPUTER 8
#define ARTIFACT_VENTS 9
#define ARTIFACT_FLOATING 10
#define ARTIFACT_CRYSTAL_GREEN 11
#define ARTIFACT_CRYSTAL_PURPLE 12
#define ARTIFACT_CRYSTAL_BLUE 13
