//infestation
#define TOTAL_HUMAN		1
#define TOTAL_ALIEN		2
#define ALIEN_PERCENT	3
#define WIN_PERCENT		150

//alien embryo
#define MAX_EMBRYO_GROWTH 40
#define MAX_EMBRYO_STAGE 5
#define FULL_EMBRYO_GROWTH MAX_EMBRYO_GROWTH * MAX_EMBRYO_STAGE
