#define SHUTTLE_FLAGS_NONE		0
#define SHUTTLE_FLAGS_PROCESS	1
#define SHUTTLE_FLAGS_SUPPLY	2
#define SHUTTLE_FLAGS_ALL		(~SHUTTLE_FLAGS_NONE)

#define SHUTTLE_JUMP_SHORT	1
#define SHUTTLE_JUMP_LONG	2

#define SHUTTLE_LOCATION_STATION 0
#define SHUTTLE_LOCATION_OFFSITE 1
