#define MODULE istype(A, /obj/item/weapon/modul_gun)
#define MODULE_ACCESSORY istype(A, /obj/item/weapon/modul_gun/accessory)
#define MODULE_MAGAZINE istype(A, /obj/item/weapon/modul_gun/magazine)
#define LENS istype(A, /obj/item/ammo_casing/energy)
#define CELL istype(A, /obj/item/weapon/stock_parts/cell)
#define MAGAZINE istype(A, /obj/item/ammo_box/magazine)