/obj/item/weapon/gun/projectile/modulargun/Destroy()
	if(barrel)
		attach(barrel, FALSE, null)
	if(grip)
		attach(grip, FALSE, null)
	if(accessory.len > 0)
		for(var/obj/item/modul in accessory)
			attach(modul, FALSE, null)
	if(accessory_type.len > 0)
		accessory_type = null
	if(lens.len > 0)
		for(var/obj/item/modul in lens)
			attach(modul, FALSE, null)
	if(magazine_module)
		attach(magazine_module, FALSE, null)
	if(chamber)
		attach(chamber, FALSE, null)
	return ..()
