/proc/captain_announce(message, title = "Priority Announcement", announcer = "")
	to_chat(world, "<h1 class='alert'>[title]</h1>")
	to_chat(world, "<span class='alert'>[message]</span>")
	if(announcer)
		to_chat(world, "<span class='alert'> -[announcer]</span>")
	to_chat(world, "<br>")
