/mob/living/silicon/Login()
	..()
	if(mind && SSticker && SSticker.mode)
		var/datum/role/cultist/C = mind.GetRole(CULTIST)
		C.RemoveFromRole(mind)
		var/datum/role/revolution/R = mind.GetRole(REV)
		R.RemoveFromRole(mind)
