arrowParens: always
bracketSpacing: true
bracketSameLine: true
endOfLine: lf
jsxSingleQuote: false
printWidth: 80
proseWrap: preserve
quoteProps: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
